global:
    resolve_timeout: 5s
    smtp_require_tls: false
route:
    receiver: admin
    group_by:
        - "123"
        - "42"
    continue: false
    group_wait: 5s
    group_interval: 5s
    repeat_interval: 5s
templates: []
